#!/bin/bash

NAME="plmstatic"                                  # Name of the application
DJANGODIR=/code						              # Django project directory
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=plm_website.settings       # which settings file should Django use
DJANGO_WSGI_MODULE=plm_website.wsgi               # WSGI module name
PORT=8000

echo "Starting $NAME"

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --bind=0.0.0.0:$PORT \
  --log-level=debug \
  --log-file=-
